# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: ms1
services:
  mysql:
    extends:
      file: ./mysql.yml
      service: mysql
  jhipster-registry:
    extends:
      file: ./jhipster-registry.yml
      service: jhipster-registry
